clear all
clc
%Quantization level
level=32;
%Loading voice
[x,fm]=audioread('audio.wav');
%Quantization
[y1, x2, errorQ] = quantize(x,level);
%Quantization error
quantization_error = strcat(num2str(errorQ),' %');

%% GUI elements
figure('Name','PCM coder/decoder using A type compression',...
           'Numbertitle','off',...  
           'Units','normalized',...    
           'Position',[0.01,0.1,0.98,0.8],...
           'Visible','on',...
           'Color','w');
    
    uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0 0.85 0.39 0.15],...
         'fontsize',20,...
         'backgroundcolor','white',...
         'foregroundcolor','black',...
         'String','PCM coder/decoder using A type compression');
     
    uicontrol('Style','push',...
             'Units','normalized',...
             'Position',[0.45 0.6 0.07 0.05],...
             'foregroundcolor','b',...
             'fontsize',11,...
             'String','Close in',...
             'BackgroundColor','[1 0 0]',...
             'Callback','subplot(3,2,2);axis([lim_inf lim_sup min(xq)-0.1 max(xq)+0.1]); subplot(3,2,4);axis([lim_inf lim_sup min(compressed)-0.1 max(compressed(lim_inf:lim_sup))+0.1]); stem(compressed); subplot(3,2,6);axis([lim_inf lim_sup min(decompressed)-0.1 max(decompressed)+0.1]);');
    uicontrol('Style','push',...
             'Units','normalized',...
             'Position',[0.45 0.4 0.07 0.05],...
             'foregroundcolor','b',...
             'fontsize',11,...
             'String','Refresh',...
             'BackgroundColor','[1 0 0]',...
             'Callback','plots(xq,compressed,decompressed);');
         
    uicontrol('Style','push',...
             'Units','normalized',...
             'Position',[0.45 0.75 0.07 0.05],...
             'foregroundcolor','b',...
             'fontsize',11,...
             'String','Listen',...
             'Callback','sound(xq,fm);');
    uicontrol('Style','push',...
             'Units','normalized',...
             'Position',[0.45 0.5 0.07 0.05],...
             'foregroundcolor','b',...
             'fontsize',11,...
             'String','Listen',...
             'Callback','sound(compressed,fm);');
    uicontrol('Style','push',...
             'Units','normalized',...
             'Position',[0.45 0.25 0.07 0.05],...
             'foregroundcolor','b',...
             'fontsize',11,...
             'String','Listen',...
             'Callback','sound(decompressed,fm);');
     
    uicontrol('Style','text',...
         'Units','normalized',...
         'Position',[0 0.02 0.2 0.15],...
         'fontsize',20,...
         'backgroundcolor','white',...
         'foregroundcolor','black',...
         'String',['Szekely Geza' newline 'Sebastian Bodea']);
         
    image1=imread('block.png');
    image(image1);
    grid off; axis off; set(gca,'Position',[0.02 0.5 0.4 0.3]);
    %Plot limits for closing in         
    lim_inf = 39950;
    lim_sup = 40050;
    
%% Compression / decompression process
%Input signal
xq=x;   
%Compression
compressed = compress(xq,max(xq));% compression by a-law
%Decompression
decompressed = decompress(compressed,max(xq));% decompression by a-law
%Plotting
plots(xq,compressed,decompressed);%displaying plots